### PR TITLE
Add type compilation testing to ci

### PR DESCRIPTION
**Pull request by gilbert**
master has some type errors, this should expose them.

### CODE REVIEW

**Comment by gilbert** [comment]
There we go. See travis build errors

**Comment by gilbert** [comment]
@martijndeh Any ideas on how to fix these type errors? I can take a stab if you're busy.

**Comment by gilbert** [comment]
Any updates? Still dreaming of using this library 😁

**Comment by martijndeh** [comment]
@gilbert I merged this one and will work on getting the type fixes in.

**Comment by gilbert** [comment]
Awesome!

**Pull request merged**
